# Generated by Django 3.2.3 on 2021-05-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Name',
            new_name='name',
        ),
    ]
